### ISSUE TITLE
Version requirements

### ISSUE THREAD

**Issue by AmaliT** [gbgolding/crema#1]
Hi @caitsimop

We are keen to trial crema on our data, however we get the following error (both on our data set and the provided example data):

```
predict.py -f crema/data/testing/athaliana_random100.fa -c crema/data/testing/athaliana_random100_cpat.txt -d crema/data/testing/athaliana_random100_blastresults.tab
Traceback (most recent call last):
  File "/opt/crema/bin/predict.py", line 33, in <module>
    clf1 = joblib.load(os.path.join(CURRENT_DIR+'/../gb_models/model1.pkl'))
  File "/usr/lib/python3/dist-packages/joblib/numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/lib/python3/dist-packages/joblib/numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
KeyError: 208
```

It seems this error might be an issue due to different versions of joblib library [see here](https://stackoverflow.com/questions/48948209/keyerror-when-loading-pickled-scikit-learn-model-using-joblib). We are using python3. Could you please let us know of the version of the packages that was used, so we can make sure we have met the prerequisite for the tool?

Cheers
Amali

**Comment by caitsimop** [comment]
Hi @AmaliT,

I'm not sure this will be very helpful, but it looks like my version of `sklearn`is v0.0 and `scikitlearn`  is v0.18.1. CREMA has been tested on Python v3.5.1.

What might be more useful is re-training the the base models using the .py files in ./crema/gb_models/  and saving the pickled models using your versions of `sklearn` and `scikitlearn`.

Let me know if you have any more questions! I'm looking forward to your results!

**Comment by AmaliT** [comment]
Hi @caitsimop 

Thank you for the information. Couple of more question

1) Could you please let us know of the version of 'joblib' library in the version you had running?
2) In terms of re-training the modules, my colleague has pointed out that given there is no record of the random value seeds used for model building, if we rebuild the model, might not be equivalent to the ones created by you. So we were wondering if it at all be possible to have conda environment to be created for crema?

Thanks again
Amali

**Comment by caitsimop** [comment]
Hi @AmaliT 

joblib was called from sklearn, and therefore came from the `scikit-learn==0.18.1`. 

We unfortunately don't have a conda python distribution on our cluster. When I tried to get a  vitrualenv working, it seems as if previous versions aren't re-installing correctly using pip3 either.

However, I just double checked, and I have set a random state in the construction of each model. See:

`clf = GradientBoostingClassifier(n_estimators=100, learning_rate= 0.04, subsample=0.6, max_depth=10, random_state=339)`

In anycase, I can upload pickled models using the most up to date modules in a couple days if that will help! 

Thanks for you patience! I'm really happy you and your collegues are helping me sort of some of the bugs when crema is used on new systems.

Caitlin

**Comment by caitsimop** [comment]
Hi @AmaliT,

I've updated the pickled models and included a requirements file for the updated models (`requirements.txt`).

`predict.py` has also been updated to point to the correct files.

Let me know if this works for you!

**Comment by AmaliT** [comment]
Great thank you @caitsimop. We will give a go and let you know.

Thanks again

**Comment by AmaliT** [comment]
Hi @caitsimop 

Could you please let us know the version of R you used, and pacman package?

Thank you
A

**Comment by caitsimop** [comment]
Hi @AmaliT,

I've tested it on R v3.5.1, R v3.3.3 and R v3.2.2 as well as pacman v0.4.6 and v0.5.0.

Caitlin

**Comment by AmaliT** [comment]
Thanks @caitsimop , We have managed to get it working
