### ISSUE TITLE
Possible bug in log_reg.R

### ISSUE THREAD

**Issue by eburgueno** [gbgolding/crema#2]
Hello, I am testing this tool in our environment and I can't get it to work against the test data. The error I am getting is the following:

```
root@9c302da2be33:/opt/crema# python3 bin/predict.py -f /opt/crema/data/testing/athaliana_random100.fa -c /opt/crema/data/testing/athaliana_random100_cpat.txt -d /opt/crema/data/testing/athaliana_random100_blastresults.tab
at1g14650.2
Loading required package: pacman
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/log_reg_models/logit_models.RData', probable reason 'No such file or directory'
Execution halted
Traceback (most recent call last):
  File "bin/predict.py", line 88, in <module>
    with open("ensemble_logreg_pred.csv") as pred:
FileNotFoundError: [Errno 2] No such file or directory: 'ensemble_logreg_pred.csv'
```

`readChar` complains about being unable to find `/log_reg_models/logit_models.RData`. I suspect this is a bug in `getScriptPath()` because the file is definitely there, just not under `/`:

```
# ls -l /opt/crema/log_reg_models/logit_models.RData 
-rw-r--r--. 1 root root 173010 Feb 15 03:00 /opt/crema/log_reg_models/logit_models.RData
```

R version is `R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"` but I see in #1 that you tested with R 3.5.1 which shouldn't be that different.

**Comment by caitsimop** [comment]
Hi @eburgueno,

I tried to recreate your error but can't seem to get the same message. I added some print statements in `log_reg.R` that might help me troubleshoot why the script can't find the file. 

    at1g14650.2  
    Loading required package: pacman  
    file path relative to current directory /opt/crema/bin  
    path to crema relative to current directory /opt/crema  
    path to logit_models.RData /opt/crema/log_reg_models/logit_models.RData
    Run successful!
    There were 3 lncRNAs predicted from /opt/crema/data/testing/athaliana_random100.fa

Would you be able to tell me which directories are printed out when you run `predict.py`?

Thanks! 
Caitlin

**Comment by eburgueno** [comment]
@caitsimop sure. Here's the output using the latest commit:

```
at1g14650.2
Loading required package: pacman
file path relative to current directory bin 
path to crema relative to current directory  
path to logit_models.RData /log_reg_models/logit_models.RData 
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/log_reg_models/logit_models.RData', probable reason 'No such file or directory'
Execution halted
Traceback (most recent call last):
  File "bin/predict.py", line 88, in <module>
    with open("ensemble_logreg_pred.csv") as pred:
FileNotFoundError: [Errno 2] No such file or directory: 'ensemble_logreg_pred.csv'
```

The result is the same if I invoke `predict.py`  directly (rather than `python3 predict.py`).

Here's my `pip freeze` in case it helps:

```
asn1crypto==0.24.0
biopython==1.73
cryptography==2.3
entrypoints==0.3
idna==2.6
keyring==17.1.1
keyrings.alt==3.1.1
numpy==1.16.1
pandas==0.24.1
pycrypto==2.6.1
PyGObject==3.30.4
python-dateutil==2.8.0
pytz==2018.9
pyxdg==0.25
scikit-learn==0.20.2
scipy==1.2.1
SecretStorage==2.3.1
six==1.12.0
```

**Comment by eburgueno** [comment]
Actually, comparing your output with mine gave me an idea. I just ran it calling it from the full path `/opt/crema/bin/predict.py` and that seems to have worked:

```
# /opt/crema/bin/predict.py -f /opt/crema/data/testing/athaliana_random100.fa -c /opt/crema/data/testing/athaliana_random100_cpat.txt -d /opt/crema/data/testing/athaliana_random100_blastresults.tab
at1g14650.2
Loading required package: pacman
file path relative to current directory /opt/crema/bin 
path to crema relative to current directory /opt/crema 
path to logit_models.RData /opt/crema/log_reg_models/logit_models.RData 
Run successful!
There were 3 lncRNAs predicted from /opt/crema/data/testing/athaliana_random100.fa
```

So clearly a bug handling the relative paths.

**Comment by caitsimop** [comment]
Hi @eburgueno,

Thanks for letting me know! 
This will be the next issue on my to-do list.

Caitlin

**Comment by caitsimop** [comment]
Pull request #4  (and subsequent merge) should have fixed this...I'm closing this issue for now.
