### ISSUE TITLE
Issue with the predict.py module

### ISSUE THREAD

**Issue by sebel76** [gbgolding/crema#7]
Hi,

Today, I try to run the full pipeline CREMA. I got an issue with the predict.py module.

-Here the bug I got:
Loading required package: pacman
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> startsWith -> contrib.url
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘pacman’
Execution halted
Traceback (most recent call last):
  File "/Users/sbelanger/software/crema/bin/predict.py", line 91, in <module>
    with open(os.path.join(fasta_path,"ensemble_logreg_pred.csv")) as pred:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sbelanger/research/project/project1/mrna/7/ensemble_logreg_pred.csv'

I did my best to find a solution, but I couldn't. Please, can you help me to solve my issue? 
If there are any program to install/uninstall or anything to change in the code architecture of my computer, please let's me know. 

In advance, thanks you for your help!

Best regards,
Sébastien Bélanger

########################################################################
1. My computer:
MacBook Pro 2019 with macOS Mojave v10.14.6
R version 3.6.1 was installed

2. Installation of requirement (all seem installed with success):
pip install atomicwrites==1.2.1
pip install attrs==18.2.0
pip install biopython==1.73
pip install certifi==2018.11.29
pip install chardet==3.0.4
pip install conda==4.3.16
pip install docopt==0.6.2
pip install goatools==0.8.9
pip install idna==2.8
pip install more-itertools==4.3.0
pip install nose==1.3.7
pip install numpy==1.16.1
pip install pandas==0.23.3
pip install patsy==0.5.1
pip install pluggy==0.8.0
pip install py==1.7.0
pip install pycosat==0.6.3
pip install pytest==3.10.0
pip install python-dateutil==2.7.3
pip install pytz==2018.5
pip install requests==2.21.0
pip install ruamel.yaml==0.15.88
pip install scikit-learn==0.20.2
pip install scipy==1.1.0
pip install six==1.11.0
pip install sklearn==0.20.0
pip install statsmodels==0.9.0
pip install treeinterpreter==0.2.2
pip install urllib3==1.24.1
pip install virtualenv==16.4.0
pip install wget==3.2
pip install xlrd==1.1.0
pip install XlsxWriter==1.1.2
conda install -c r r-pacman

3. Code used:

#! /bin/bash
####################################################
####################################################
#PATH
dir1="/Users/sbelanger/research/project/project1/mrna/7/"
dir2="/Users/sbelanger/software/crema"
prot="/Users/sbelanger/research/data/reference/protein/"
ref1="/Users/sbelanger/research/data/reference/H.vulgare"
ref2="/Users/sbelanger/research/data/reference/T.aestivum"
ncrna1="/Users/sbelanger/research/data/reference/H.vulgare/Hordeum_vulgare.IBSC_v2.ncrna.fa"
ncrna2="/Users/sbelanger/research/data/reference/T.aestivum/Triticum_aestivum.IWGSC.ncrna.fa"
cds1="/Users/sbelanger/research/data/reference/H.vulgare/Hordeum_vulgare.IBSC_v2.cds.all.fa"
cds2="/Users/sbelanger/research/data/reference/T.aestivum/Triticum_aestivum.IWGSC.cds.all.fa"
cdna1="/Users/sbelanger/research/data/reference/H.vulgare/Hordeum_vulgare.IBSC_v2.cdna.all.fa"
cdna2="/Users/sbelanger/research/data/reference/T.aestivum/Triticum_aestivum.IWGSC.cdna.all.fa"

#STEP1: To build perequist data:
cd /Users/sbelanger/research/project/project1/mrna/7/
make_hexamer_tab.py -c ${cds1} -n ${ncrna1} > CPAT/hexamer_hvu
make_hexamer_tab.py -c ${cds2} -n ${ncrna2} > CPAT/hexamer_tae

make_logitModel.py --hex=CPAT/hexamer_hvu -c ${cdna1} -n ${ncrna1} -o CPAT/hvu
make_logitModel.py --hex=CPAT/hexamer_tae -c ${cdna2} -n ${ncrna2} -o CPAT/tae

#STEP2: Run CPAT
cd /Users/sbelanger/research/project/project1/mrna/7/
cpat.py -g hvu_unknown_GP.fa -o CPAT/cpat_hvu_unknown_GP.txt -x CPAT/hexamer_hvu -d CPAT/hvu.logit.RData
cpat.py -g hvu_unknown_M.fa -o CPAT/cpat_hvu_unknown_M.txt -x CPAT/hexamer_hvu -d CPAT/hvu.logit.RData
cpat.py -g tae_unknown_F.fa -o CPAT/cpat_tae_unknown_F.txt -x CPAT/hexamer_tae -d CPAT/tae.logit.RData

#STEP3: Run DIAMOND
cd ${prot} 
diamond makedb --in uniprot_sprot.fasta -d swissprot.dmnd

cd ${dir1}
diamond blastx -d ${prot}/swissprot.dmnd -q hvu_unknown_GP.fa -o DIAMOND/hvu_diamond_output_GP.txt -e 0.001 -k 5 --matrix BLOSUM62 --gapopen 11 --gapextend 1 --more-sensitive -f 6 qseqid pident length qframe qstart qend sstart send evalue bitscore
diamond blastx -d ${prot}/swissprot.dmnd -q hvu_unknown_M.fa -o DIAMOND/hvu_diamond_output_M.txt -e 0.001 -k 5 --matrix BLOSUM62 --gapopen 11 --gapextend 1 --more-sensitive -f 6 qseqid pident length qframe qstart qend sstart send evalue bitscore
diamond blastx -d ${prot}/swissprot.dmnd -q tae_unknown_F.fa -o DIAMOND/tae_diamond_output_F.txt -e 0.001 -k 5 --matrix BLOSUM62 --gapopen 11 --gapextend 1 --more-sensitive -f 6 qseqid pident length qframe qstart qend sstart send evalue bitscore

#STEP4: Run CREME
cd ${dir2}
python3 /Users/sbelanger/software/crema/bin/predict.py -f ${dir1}/hvu_unknown_GP.fa -c ${dir1}/CPAT/cpat_hvu_unknown_GP.txt -d ${dir1}/DIAMOND/hvu_diamond_output_GP.txt > ${dir1}/hvu_crema_oout_GP.txt

**Comment by caitsimop** [comment]
Hi @sebel76,

`predict.py` also calls an R script, and it looks like it's not installing the package that you need. Could you try installing `pacman` in R using `install.packages("pacman")`?

**Comment by sebel76** [comment]
Hi,

Thanks you for your quick reply. It seem that I could run it properly. I first install pacman in the terminal window used, and then, I could run predict.py. 

Thanks!
Sébastien

**Comment by caitsimop** [comment]
Great, glad it helped! I'm closing this issue for now, but let me know if anything else pops up.

Cheers,
Caitlin
