### ISSUE TITLE
New bug 

### ISSUE THREAD

**Issue by sebel76** [gbgolding/crema#9]
Hi,

This morning, I used CREMA with a new set of transcript to analyze. When using the script predict.py, I got the following message:

Traceback (most recent call last):
  File "/Users/sbelanger/software/crema/bin/predict.py", line 45, in <module>
    trans_info, trans_dict, trans_names = transcript_info_dict(args.trans_fasta, args.cpat_out, args.diam_out)
  File "/Users/sbelanger/software/crema/bin/featuresetup_module.py", line 82, in transcript_info_dict
    transcript_info_array = np.array([[transcript_dict[gene][feature] for feature in sorted(transcript_dict[gene])] for gene in name_list], dtype=float)
ValueError: setting an array element with a sequence.

Please, can you help me? Did I do something wrong? I used exactly the same code than previously except that I changed transcript as entry.

Thanks to help me!
Sébastien
##########
#Script used:

#! /bin/bash
###############################################################
###############################################################
#PATH
dir1="/Users/sbelanger/research/project/project1/mrna/5"
dir2="/Users/sbelanger/software/crema"
prot="/Users/sbelanger/research/data/reference/protein/"
ref1="/Users/sbelanger/research/data/reference/H.vulgare"
ref2="/Users/sbelanger/research/data/reference/T.aestivum"
ncrna1="/Users/sbelanger/research/data/reference/H.vulgare/Hordeum_vulgare.IBSC_v2.ncrna.fa"
ncrna2="/Users/sbelanger/research/data/reference/T.aestivum/Triticum_aestivum.IWGSC.ncrna.fa"
cds1="/Users/sbelanger/research/data/reference/H.vulgare/Hordeum_vulgare.IBSC_v2.cds.all.fa"
cds2="/Users/sbelanger/research/data/reference/T.aestivum/Triticum_aestivum.IWGSC.cds.all.fa"
cdna1="/Users/sbelanger/research/data/reference/H.vulgare/Hordeum_vulgare.IBSC_v2.cdna.all.fa"
cdna2="/Users/sbelanger/research/data/reference/T.aestivum/Triticum_aestivum.IWGSC.cdna.all.fa"

#STEP1: To build perequist data:
cd /Users/sbelanger/research/project/project1/mrna/5
make_hexamer_tab.py -c ${cds1} -n ${ncrna1} > CPAT/hexamer_hvu
make_hexamer_tab.py -c ${cds2} -n ${ncrna2} > CPAT/hexamer_tae

make_logitModel.py --hex=CPAT/hexamer_hvu -c ${cdna1} -n ${ncrna1} -o CPAT/hvu
make_logitModel.py --hex=CPAT/hexamer_tae -c ${cdna2} -n ${ncrna2} -o CPAT/tae

# STEP2: Run CPAT
cd /Users/sbelanger/research/project/project1/mrna/5
cpat.py -g hvu-merged.fa -o CPAT/cpat_hvu-merged.txt -x CPAT/hexamer_hvu -d CPAT/hvu.logit.RData
cpat.py -g tae-merged.fa -o CPAT/cpat_tae-merged.txt -x CPAT/hexamer_tae -d CPAT/tae.logit.RData

#STEP3: Run DIAMOND
cd ${prot} 
diamond makedb --in uniprot_sprot.fasta -d swissprot.dmnd

cd /Users/sbelanger/research/project/project1/mrna/5
diamond blastx -d ${prot}/swissprot.dmnd -q hvu-merged.fa -o DIAMOND/hvu_diamond_output_merged.txt -e 0.001 -k 5 --matrix BLOSUM62 --gapopen 11 --gapextend 1 --more-sensitive -f 6 qseqid pident length qframe qstart qend sstart send evalue bitscore
diamond blastx -d ${prot}/swissprot.dmnd -q tae-merged.fa -o DIAMOND/tae_diamond_output_merged.txt -e 0.001 -k 5 --matrix BLOSUM62 --gapopen 11 --gapextend 1 --more-sensitive -f 6 qseqid pident length qframe qstart qend sstart send evalue bitscore

#STEP4: Run CREME
R
install.packages("pacman")
1
q()
y

cd /Users/sbelanger/research/project/project1/mrna/5
python3 /Users/sbelanger/software/crema/bin/predict.py -f hvu-merged.fa -c CPAT/cpat_hvu-merged.txt -d DIAMOND/hvu_diamond_output_merged.txt > CREMA/hvu_crema_out.txt
python3 /Users/sbelanger/software/crema/bin/predict.py -f tae-merged.fa -c CPAT/cpat_tae-merged.txt -d DIAMOND/tae_diamond_output_merged.txt > CREMA/tae_crema_out.txt

**Comment by caitsimop** [comment]
Hi Sébastian,

It seems like your new files may be in the wrong format. Can you double check this for me?

Cheers,
Caitlin

**Comment by sebel76** [comment]
Hi Caitlin,

Yes, I doubled check! This is a Fasta file format!

**Comment by caitsimop** [comment]
It's difficult to troubleshoot without the actual file. Would you be willing to send me the file?

**Comment by sebel76** [comment]
Yes, sure! My file have 547 MB... Do you have a way to send you this file? I want to keep this file private...

**Comment by caitsimop** [comment]
Please email me a subset of this file (maybe 20-25 sequences) to: caitlin.simopoulos@gmail.com

Caitlin
